### ISSUE TITLE
getRelativePathname() error

### ISSUE THREAD

**Issue by ngya** [Druki-ru/website#10]
hi, i build the site step by step, but i don't import conents.
then i add a druki content, it will show this:

`TypeError: Return value of Drupal\druki_content\Entity\DrukiContent::getRelativePathname() must be of the type string, null returned in Drupal\druki_content\Entity\DrukiContent->getRelativePathname() (line 163 of D:\xampp\htdocs\druki\web\modules\custom\druki_content\src\Entity\DrukiContent.php) `

but if i import contents, everything is ok. 

so what's wrong?

**Comment by Niklan** [comment]
Hi, what is your purpose?

This entity is intended to be managed by remote content and programmatically. The entity form only for testing and hotfix editing (if needed) not for creating content.

**Comment by Niklan** [comment]
The only thing I can propose to do here is block entity form when it's used to create new content and add note that this behavior is not intended.

**Comment by ngya** [comment]
i know the default entity form is block.
![image](https://user-images.githubusercontent.com/3828979/90519550-bff5ed80-e19a-11ea-9ef7-49b0705ebcbe.png)
i mean this button, and i want to add new wiki content. 
when i click the button, it will show `getRelativePathname() error `

**Comment by Niklan** [comment]
Yes, this button used at the very beginning of development. Not intended for use now. Must be removed. Content for Druki Content entity expected to be processed via all pipeline and external files.

**Comment by ngya** [comment]
ok, i got it. thx.
 in addition, i learn a lot from your site.  :)
