### ISSUE TITLE
Проблема с подсветкой кода в тёмном режиме

### ISSUE THREAD

**Issue by Niklan** [Druki-ru/website#109]
Цвет класса тёмного цвета, нужно задать цвет для тёмного варианта как в шторме:

![image](https://user-images.githubusercontent.com/2356744/141669464-e1d53197-3c12-4d05-96c7-4728c381cf5a.png)

Должен быть: `rgb(169, 183, 198)`;

**Comment by Niklan** [comment]
https://github.com/Druki-ru/website/blob/aac14fda7fbb9f9adde7fcdf76d0487f3ed81a19/web/themes/custom/loremaster/assets/css/04-components/javascript/prismjs.pcss#L9

^ CSS переменная что нужно добавить сюда с нужным цветом (`rgb(169, 183, 198)`):

https://github.com/Druki-ru/website/blob/aac14fda7fbb9f9adde7fcdf76d0487f3ed81a19/web/themes/custom/loremaster/assets/css/04-components/javascript/prismjs.pcss#L20-L31

**Comment by chesn0k** [comment]
Я исправилю
