### ISSUE TITLE
Проблема синхронизации

### ISSUE THREAD

**Issue by a-kovrigin** [Druki-ru/website#126]
При попытке синхронизации контента, процесс импорта из репозитория контента может не выполняться.
Текст ошибки: `"git" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом`
Скорее всего проблема в том, что обращение к git может иметь разный путь в различных окружениях.

### Возможное решение
Предоставить настройку для указания пути до исполняемого git и использовать этот путь в методах объекта [Git](https://github.com/Druki-ru/website/blob/80488dcfe7cbc63dc3c7d056a8f65cd484e50f24/web/modules/custom/druki/src/Process/Git.php#L34).

Например, метод `pull` мог бы выглядеть так:
```php
/**
 * {@inheritdoc}
 */
public function pull(string $directory): Process {
  // @see https://stackoverflow.com/a/62653400/4751623
  $command = [$this->gitExecutePath, 'pull', '--ff-only'];
  return $this->terminal->createProcess($command, $directory);
}`

**Comment by Niklan** [comment]
Подозреваю что лучше всего будет добавить поддержку переопределения пути до бинарника в `settings.php`. Чтобы это зависило от окружения, а не конфигурации для всех.

Что нужно сделать:

- В `Drupal\druki\Process\Git` добавить новое свойство `$gitBinary`.
- В конструкторе задавать значение для этого свойства: `$this->gitBinary = Settings::get('druki_git_binary', 'git');`
- Во всех вызовах где используется `'git'`, заменить на `$this->gitBinary` (как в примере самого ишью).
- Добавить в README.md информацию об этой настройке.
