### ISSUE TITLE
Исправить парсер для ссылок

### ISSUE THREAD

**Issue by DimaSuharchuk** [Druki-ru/website#27]
строка https://github.com/Druki-ru/website/blob/50d3fc56acc14a746cf7c45c859c9d3807da8b67/web/modules/custom/druki_content/src/Plugin/Filter/InternalLinks.php#L91

Добавить пробел после "`<a`", тоесть получится "`<a `". 
Потому что сейчас пропустит все теги, которые начинаются на "а", а не только ссылки.

**Comment by Niklan** [comment]
Попробовать искать вообще по `data-druki-internal-link-filepath`, так как не все ссылки нужны, а только внутренние.
