### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ghost** [Druki-ru/website#67]
Dear Developer!

I found several errors during the installation:
`
    The configuration synchronization failed validation.
    Unable to install the config_filter module since it does not exist.
`
`
    The configuration synchronization failed validation.
    Unable to install the druki_installer module since it does not exist.
`

please fix the bug so that the installation can be used.

Regards,
The Lacesz

**Comment by Niklan** [comment]
Thank you for reporting this!
