### ISSUE TITLE
Добавить поддержку файлов для авторов

### ISSUE THREAD

**Issue by Niklan** [Druki-ru/website#73]
Данный функционал можно использовать для отображения тех, кто работал над документом и т.д., без необходимости думать как парсить инфу, обновлять, инвалидировать, откуда отдавать картинки и т.д.

Можно как у гугла, создать json файл в контент репе с информацией об авторах:

https://github.com/GoogleChrome/web.dev/blob/147c161bbc8644e6a244e40a0c49f2d9cc7f7df8/src/site/_data/authorsData.json

В коммитах можно парсить авторов по email и выводить всю инфу. Фотки и прочая инфа также будет в репе.

Надо решить какие данные, как и где хранить.

**Comment by chesn0k** [comment]
Упомяну здесь обсуждение где мы говорили про не надежность контроля авторства по email.

Email будет отличаться в коммитах сделанных в git и GitHub UI, если он будет скрытым в настройках аккаунта GitHub.

Предлагаю использовать ник для парсинга авторства.
