### ISSUE TITLE
Где settings.php до установки взять?

### ISSUE THREAD

**Issue by PVasili** [Druki-ru/website#85]
По инструкции ("Add this line $config['config_split.config_split.dev']['status'] = TRUE; to settings.php.")  
И где лежит settings.php до установки? 
Дальше по тексту — аналогично: "Add $settings['config_sync_directory'] = '../config/sync'; to your settings.php"…

**Comment by chesn0k** [comment]
Скопируйте `default.settings.php` и переименуйте в `settings.php`

**Comment by PVasili** [comment]
До установки или после?
А сразу написать об этом можно в инструкции, чтобы начинающие не разгадывали ребусы.

**Comment by chesn0k** [comment]
Перед запуском скрипта установки

**Comment by PVasili** [comment]
Ну так и напишите: скопируйте из ... /default.settings.php и переименуйте в .../settings.php  
99% об этом даже не догадываются.

**Comment by PVasili** [comment]
После 6 пункта 
`Notice: Undefined index: twig_tweak in Drupal\Core\EventSubscriber\ConfigImportSubscriber->validateThemes() (line 187 of core\lib\Drupal\Core\EventSubscriber\ConfigImportSubscriber.php).
Drupal\Core\EventSubscriber\ConfigImportSubscriber->validateThemes(Object) (Line: 76)
Drupal\Core\EventSubscriber\ConfigImportSubscriber->onConfigImporterValidate(Object, 'config.importer.validate', Object)
call_user_func(Array, Object, 'config.importer.validate', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'config.importer.validate') (Line: 747)
Drupal\Core\Config\ConfigImporter->validate() (Line: 534)
Drupal\Core\Config\ConfigImporter->initialize() (Line: 2340)
install_config_import_batch(Array) (Line: 619)
install_run_task(Array, Array) (Line: 565)
install_run_tasks(Array, NULL) (Line: 118)
install_drupal(Object) (Line: 48)
Notice: Trying to get property 'info' of non-object in Drupal\Core\EventSubscriber\ConfigImportSubscriber->validateThemes() (line 187 of core\lib\Drupal\Core\EventSubscriber\ConfigImportSubscriber.php).
Drupal\Core\EventSubscriber\ConfigImportSubscriber->validateThemes(Object) (Line: 76)
Drupal\Core\EventSubscriber\ConfigImportSubscriber->onConfigImporterValidate(Object, 'config.importer.validate', Object)
call_user_func(Array, Object, 'config.importer.validate', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'config.importer.validate') (Line: 747)
Drupal\Core\Config\ConfigImporter->validate() (Line: 534)
Drupal\Core\Config\ConfigImporter->initialize() (Line: 2340)
install_config_import_batch(Array) (Line: 619)
install_run_task(Array, Array) (Line: 565)
install_run_tasks(Array, NULL) (Line: 118)
install_drupal(Object) (Line: 48)
Notice: Undefined index: twig_tweak in Drupal\Core\EventSubscriber\ConfigImportSubscriber->validateThemes() (line 187 of core\lib\Drupal\Core\EventSubscriber\ConfigImportSubscriber.php).
Drupal\Core\EventSubscriber\ConfigImportSubscriber->validateThemes(Object) (Line: 76)
Drupal\Core\EventSubscriber\ConfigImportSubscriber->onConfigImporterValidate(Object, 'config.importer.validate', Object)
call_user_func(Array, Object, 'config.importer.validate', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'config.importer.validate') (Line: 747)
Drupal\Core\Config\ConfigImporter->validate() (Line: 534)
Drupal\Core\Config\ConfigImporter->initialize() (Line: 2340)
install_config_import_batch(Array) (Line: 619)
install_run_task(Array, Array) (Line: 565)
install_run_tasks(Array, NULL) (Line: 118)
install_drupal(Object) (Line: 48)
Notice: Trying to get property 'info' of non-object in Drupal\Core\EventSubscriber\ConfigImportSubscriber->validateThemes() (line 187 of core\lib\Drupal\Core\EventSubscriber\ConfigImportSubscriber.php).
Drupal\Core\EventSubscriber\ConfigImportSubscriber->validateThemes(Object) (Line: 76)
Drupal\Core\EventSubscriber\ConfigImportSubscriber->onConfigImporterValidate(Object, 'config.importer.validate', Object)
call_user_func(Array, Object, 'config.importer.validate', Object) (Line: 142)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'config.importer.validate') (Line: 747)
Drupal\Core\Config\ConfigImporter->validate() (Line: 534)
Drupal\Core\Config\ConfigImporter->initialize() (Line: 2340)
install_config_import_batch(Array) (Line: 619)
install_run_task(Array, Array) (Line: 565)
install_run_tasks(Array, NULL) (Line: 118)
install_drupal(Object) (Line: 48)
The configuration synchronization failed validation.
Unable to install the Glisseo (base theme) theme since it requires the theme.
Unable to install the Loremaster theme since it requires the theme.`

:(

**Comment by PVasili** [comment]
не взлетело :(

**Comment by PVasili** [comment]
12 таблиц добавилось…
https://dropmefiles.net/ru/UTYckhs5Cx   глукнутая копия (если интересно)

**Comment by Niklan** [comment]
@PVasili `composer install` запускался, прошел без ошибок? Потому что похоже что попались на этот баг:

> **Warning!** Currently, Drupal core has a bug [#3176625](https://www.drupal.org/project/drupal/issues/3176625). Before it resolved, you must patch core before running installation process, otherwise it will fail during config imports. Nothing can be done from our side. _The current version of codebase include that patch._

А раз он воспроизвёлся с актуальной версией — патч не применился.

**Comment by Niklan** [comment]
Так как ишью без активности, закрываю. Будут вопросы - переоткройте или создайте новое.
