### ISSUE TITLE
The RSS feed

### ISSUE THREAD

**Issue by ghost** [Druki-ru/website#87]
Is there any rss feed available to follow for new articles?

**Comment by Niklan** [comment]
Hi @o771e,

Sorry, but no. I don't even understand how this should work. Many articles update frequently, can be deleted and recreated, and pushing each time it happens into RSS will be very annoying. Moreover, there is possibility to rebuild all content and this will trigger to all content ping in RSS.

I think the proper way, if you interested only in content, is to subscribe to content repository commits RSS: https://github.com/Druki-ru/content/commits/master.atom

**Comment by Niklan** [comment]
I am closing this issue, if you still have questions open it or a new issue.
